language: php
cache:
  directories:
  - vendor
php:
  - 5.6
  - 5.5
  - 5.4
  - nightly

matrix:
  allow_failures:
    - php: nightly
  
before_script:
  - mkdir -p ~/.rezzza/php/extensions && cd ~/.rezzza/php/extensions \
    && git clone --depth=50 https://github.com/nicolasff/phpredis \
    && cd phpredis \
    && phpize \
    && echo "Configuring phpredis..." \
    && ./configure > /dev/null \
    && echo "Building phpredis..." \
    && make -j4 > /dev/null \
    && echo "Installing phpredis..." \
    && sudo make install > /dev/null
  - alias composer="php -d zend.enable_gc=0 /usr/bin/composer"
  - composer require --dev satooshi/php-coveralls:dev-master
  - composer install
  
after_script:
  - export COVERALLS_RUN_LOCALLY=1
  - php bin/coveralls -v

script: 
  - bin/phpunit --coverage-text
  - bin/phpunit-randomizer --order rand

matrix:
     allow_failures:
         - php: nightly  
