imports:
    - { resource: cache_parameters.yml }

services:
    nil_portugues.cache.adapter.in_memory_adapter:
        class: NilPortugues\Cache\Adapter\InMemoryAdapter

    nil_portugues.cache.adapter.sql.mysql_adapter:
        class: NilPortugues\Cache\Adapter\SQL\MySqlAdapter
        arguments:
          - [%mysql_server.master%]
          - @nil_portugues.cache.adapter.in_memory_adapter

    nil_portugues.cache.adapter.redis.native_adapter:
        class: NilPortugues\Cache\Adapter\Redis\NativeAdapter
        arguments:
          - [%redis_servers%]
          - @nil_portugues.cache.adapter.in_memory_adapter
          
    nil_portugues.cache.adapter.redis.predis_adapter:
        class: NilPortugues\Cache\Adapter\Redis\PredisAdapter
        arguments:
          - [%redis_servers%]
          - @nil_portugues.cache.adapter.in_memory_adapter

    nil_portugues.cache:
        class: NilPortugues\Cache\Cache
        arguments:
          - @nil_portugues.cache.adapter.redis.native_adapter
          - "namespaced.cache"
