imports:
    - { resource: cache_parameters.yml }

services:
    nil_portugues.cache:
        class: NilPortugues\Cache\Cache
        arguments: 
          - @nil_portugues.cache.adapter.in_memory_adapter

    nil_portugues.cache.adapter.in_memory_adapter:
        class: NilPortugues\Cache\Adapter\InMemoryAdapter
