parameters:
  filesystem_config:
    - path: /var/tmp
    - default_expires: 0
    
  mysql_config:
    - host: localhost
    - port: 3306
    - database: ""
    - default_expires: 0
    
  sqlite_config:
    - host: localhost
    - port: 3306
    - database: ""
    - default_expires: 0
    
  sphinxql_config:
    - host: localhost
    - port: 3306
    - database: ""
    - default_expires: 0
    
  mongodb_config:
    - host: localhost
    - port: 3306
    - database: ""
    - default_expires: 0
    
  memcached_config:
    - host: localhost
    - port: 3306
    - database: ""
    - default_expires: 0
    
  elasticsearch_config:
    - host: localhost
    - port: 3306
    - database: ""
    - default_expires: 0
    
  redis_config:
    - host: localhost
    - port: 3306
    - database: ""
    - default_expires: 0
