imports:
    - { resource: cache_parameters.yml }

services:
    nil_portugues.cache:
        class: Path\To\Class
        arguments: 
          - @nil_portugues.cache.adapter.in_memory_adapter

    nil_portugues.cache.adapter.in_memory_adapter:
        class: Path\To\Class
